language: minimal

matrix:
  include:
    - name: "Debian 10 (Buster)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} debian_buster"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name debian_buster --rm debian:buster
      after_success:
        - docker kill debian_buster
    
    - name: "Ubuntu 18.04 (Bionic)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} -e DEBIAN_FRONTEND=noninteractive ubuntu_bionic"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ubuntu_bionic --rm ubuntu:bionic
      after_success:
        - docker kill ubuntu_bionic
    
    - name: "Ubuntu 20.04 (Focal)"
      os: linux
      sudo: required
      services:
        - docker
      env: 
        - CI_TYPE=deb
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER="docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} -e DEBIAN_FRONTEND=noninteractive ubuntu_focal"
      before_install:
        - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ubuntu_focal --rm ubuntu:focal
      after_success:
        - docker kill ubuntu_focal
    
    # The current build depends on Odil obtained through homebrew. Since this is
    # in a non-official tap, any upgrade of a dependency of Odil will break the
    # whole build.
    - name: "macOS 10.14 (Mojave)"
      os: osx
      osx_image: xcode11
      env: 
        - CI_TYPE=conda_mac
        - CMAKE_OPTIONS="-DBoost_NO_BOOST_CMAKE=ON"
        - WORKSPACE=${TRAVIS_BUILD_DIR}
        - RUNNER=""
    
script: |
  ${RUNNER} ./.ci/${CI_TYPE}/install && ${RUNNER} ./.ci/${CI_TYPE}/build && ${RUNNER} ./.ci/${CI_TYPE}/post_build
